Feature/aos 3830 nytt endepunkt for fjerning av pods
Skatteetaten/clerk pull request #10
Opened 2019-12-02 11:43 UTC by stromland

2019-12-03 07:29 UTC, bjartek approved these changes

2019-12-03 07:31 UTC, bjartek requested changes
Vet ikke om denne var klar for review enda, men vi mangler vel noen tester her?

2019-12-04 11:07 UTC, jarlehansen requested changes

2019-12-04 11:07 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/clerk/controller/ApplicationController.kt
> +            throw RuntimeException(
Grunn til at denne kastes videre som RuntimeException?
Kanskje vi kunne laget en ClerkException eller kanskje til og med noe mer spesifikt?

2019-12-04 11:07 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/clerk/service/DeploymentConfigServiceTest.kt
> +    private val podService: PodService = mockk()
Jeg tror denne testen burde kjøres med `@TestInstance(TestInstance.Lifecycle.PER_METHOD)` og 

```
@AfterEach
fun after() {
  HttpMock.clearAllHttpMocks()
}
```

2019-12-04 11:25 UTC, stromland commented on src/main/kotlin/no/skatteetaten/aurora/clerk/controller/ApplicationController.kt
> +            throw RuntimeException(
Det var en annen kontroller som gjorde det på den måten så tenkte å følge samme måte. Men vi kan godt lage en ny exception.

2019-12-05 12:43 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/clerk/service/DeploymentConfigService.kt
> +        client.serviceAccount().deletePod(namespace, name).blockForResource()
retry this with exponential backoff and remove the sleep?

2019-12-05 12:45 UTC, bjartek requested changes
remove sleep and retry

2019-12-06 08:40 UTC, bjartek approved these changes

2019-12-18 08:17 UTC, merged